app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap


from config import config


boot = Bootstrap()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    boot.init_app(app)

    #blueprints
    from app.portfolio import portfolio
    app.register_blueprint(portfolio, url_prefix='/portfolio/')
    print(app.url_map)
    return app

app/portfolio/__init__.py
from flask import Blueprint
portfolio = Blueprint('portfolio', __name__)
from . import views

app/portfolio/views.py
from . import portfolio
from flask import jsonify, make_response, send_file, Response, request, stream_with_context
import json
from flask import render_template, url_for, redirect
import os
from datetime import datetime

static_folder_pro = "../static/projects/projects.json"
static_folder_tln = "../static/timeline/timeline.json"


@portfolio.route('/')
def home():

    return render_template("home.html", title='home', username="carlos")


@portfolio.route('/projects')
def projects():
    data = get_static_json(static_folder_pro)['projects']
    data.sort(key=order_projects_by_weight, reverse=True)

    tag = request.args.get('tags')
    if tag is not None:
        data = [project for project in data if tag.lower() in [project_tag.lower() for project_tag in project['tags']]]

    return render_template('projects.html', projects=data, tag=tag)


def get_static_json(path):
    return json.load(open(get_static_file(path)))


def order_projects_by_weight(projects):
    try:
        return int(projects['weight'])
    except KeyError:
        return 0


def get_static_file(path):
    site_root = os.path.realpath(os.path.dirname(__file__))
    return os.path.join(site_root, path)


@portfolio.route('/projects/<title>')
def project(title):
    projects = get_static_json(static_folder_pro)['projects']

    in_project = [p for p in projects if p['link'] == title]

    if in_project is not None:
        selected = in_project
    return render_template('project.html', project=selected)

@portfolio.route('/timeline/')
def timeline():
    data = get_static_json(static_folder_tln)['timeline']
    data.sort(key=order_timeline, reverse=True)
    return render_template('timeline.html', timeline=data)


def order_timeline(timeline):
    try:
        return int(timeline['year'])
    except KeyError:
        return 0

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--fonts-->
    <link rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Source+Code+Pro:400,500,600,700'
          type='text/css' media='screen'/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:900" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/base.css') }}">

    <!--tracking-->
    <script>
        window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
        ga('create', '{{config.GA_TRACKING_ID}}', 'auto');

        // Replace the following lines with the plugins you want to use.
        ga('require', 'eventTracker');
        ga('require', 'outboundLinkTracker');
        ga('require', 'urlChangeTracker');
        ga('require', 'cleanUrlTracker');
        ga('require', 'maxScrollTracker');
        ga('require', 'impressionTracker');
        ga('require', 'outboundLinkTracker');
        ga('require', 'pageVisibilityTracker');
        // ...
        ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    <script async src="{{url_for('static', filename = 'js/autotrack.js') }}"></script>

    {% block head %}
    {% endblock %}
</head>
<body>
<div class="navbar-ul">
    <ul id="navbar-list" class="list-inline">
        <li><a class="navbar-ref" href="{{ url_for('portfolio.home') }}">Home</a></li>
        <li><a class="navbar-ref" href="{{ url_for('portfolio.timeline') }}">Timeline</a></li>
        <li><a class="navbar-ref" href="{{ url_for('portfolio.projects') }}">Projects</a></li>

    </ul>
    <audio controls="controls" autoplay="loop" src="{{ url_for('static', filename = 'music/avantasia.mp3') }}" type="file/mpeg">

</iframe>
    </audio>
</div>
{% block body %}
{% endblock %}
</body>
</html>

app/templates/card.html
<div class="col s12 m4 l4">
    <div class="card hoverable">
        <div class="card-image waves-effect waves-block waves-light">
            {% if 'photos' in project %}
            <img class="card-image activator" src={{project['photos'][0]}}/>
            {% else %}
            <img class="card-image activator" src="/static/images/projectx.png/">
            {% endif %}
        </div>
        <div class="card-content activator">
            <div class="container-outer">
                <div class="md-chips container-inner">
                    {% for tag in project['tags'] %}
                    <div class="md-chip md-chip-clickable"><a class="md-chip-link"
                                                              href="">{{tag}}</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div>
            <span id="title" class="card-title activator grey-text text-darken-4" title="{{project['name']}}">
              {{project['name']}}
            </span>
                <i class="material-icons right activator">more_vert</i>
            </div>
            <div>

                {% if 'github' in project %}
                <span><a class="github" href={{project['github']}}> | Github</a></span>
                {% endif %}

            </div>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{{project['name']}}<i
                    class="material-icons right">close</i></span>
            <div><span class="status">{{project['date']}}</span></div>
            <p>{{project['short']}}</p>

        </div>
    </div>
</div>

app/templates/home.html
{% extends "base.html" %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<link type="text/css" rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<script src='https://cdnjs.cloudflare.com/ajax/libs/typed.js/1.1.1/typed.min.js'></script>

<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/home.css') }}">
<script type="text/javascript" src="{{ url_for('static', filename = 'js/home.js') }}"></script>
{% endblock %}

{% block body %}
<div class="container">
    <div class="wrapper fixed-wrapper">
        <section id="terminal">
            <div id="terminal-container">
                <div class="terminal">
                    <div class="window-title">
                        <div class="win-buttons">
                            <a id="close" class="button" href="#"></a>
                            <a id="min" class="button" href="#"></a>
                            <a id="max" class="button" href="#"></a>
                        </div>
                        <span class="title">oh-my-zsh</span>
                    </div>
                    <div class="message">
                        <span class='prompt'><span class='user'>creator</span><span class="at">@</span><span
                                class="path">/home/carlos/</span>><span class="caret">$</span></span>
                        <span class="typed"></span>
                        <form>><span class="caret">$</span>&nbsp;<input type="text" name="response"/></form>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="wrapper scroll-wrapper">
        <div class="top-text">
            <p class="text-title desktop-view">Carlos</p>
            <p class="text-title desktop-view">Espinoza</p>
            <p class="text-title mobile-view">Carlos Espinoza</p>
            <div class="social-icons">
                <a target="_blank" href="https://github.com/venatur">
                    <img class="title-logo" src="{{url_for('static',filename='images/github.svg')}}">
                </a>
                <a target="_blank" href="https://www.linkedin.com/in/carlos-espinoza-garcia-250b33132/">
                    <img class="title-logo" src="{{url_for('static',filename='images/linkedin-logo.svg')}}">
                </a>
                <a target="_blank" href="https://twitter.com/caldos69">
                    <img class="title-logo" src="{{url_for('static',filename='images/twitter.svg')}}/">
                </a>

            </div>
        </div>
        <div class="middle-text">
            <p class="text-content">Hi, I'm a dreamer that believes on tecnology to live in a better world.</p>
            <p class="text-content">
                I live in Mexicali, Baja California Mexico, I'm 32 years old. I’m Studying a Master degree in Data science applied on distribuited systems.
                I’m currently working on my Covid-19 project, it’s aimed to study all data gathered from mexican federation and expose it to scientific groups with analysis purposes.</p>

            <p class="text-content">I'm studying my Master at <a href="http://institutodeingenieria.uabc.mx/">Instituto de ingenieria de Baja California</a>.
            </p>

            <p class="text-content">One of my best projects is an applications build in python to retrive all national data related to COVID-19 besides
                I developed an API to serve the results to anyone that knows JSON and XML</p>


            <p class="text-content">You can find me on <a href="https://www.linkedin.com/in/carlos-espinoza-garcia-250b33132/">LinkedIn</a>,
                or email me <a href="mailto:isc.caeg@gmail.com?Subject=Hello%Carlos%20-from-website" target="_top">here</a>.
            </p>

            <p class="text-content">Let's get in touch!</p>

            <p class="text-content">Carlos Espinoza</p>

            <p class="text-content"><a href="timeline">For more about me, my timeline, read on here.</a></p>

            <br>
        </div>
    </div>
</div>
{% endblock %}

app/templates/project.html
{% extends "base.html" %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/project.css') }}">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/chip.css') }}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock %}

{% block body %}
<div class="container">
    <div class="wrapper fixed-wrapper">

        {% if 'photos' in project or 'videos' in project %}
        <div>
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false" ;>
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for video in project['videos'] %}
                    <li data-target="#myCarousel" data-slide-to="loop.index0"
                        class="{{'active' if loop.index0 == 0}}"></li>
                    {% endfor %}
                    {% for photo in project['photos'] %}
                    <li data-target="#myCarousel" data-slide-to="loop.index0"
                        class="{{'active' if ((loop.index0 == 0) and (not 'videos' in project)) }}"></li>
                    {% endfor %}
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% for video in project['videos'] %}
                    <div class="item {{'active' if loop.index0 == 0}}">
                        {{ project['videos'][loop.index0] | safe }}
                    </div>
                    {% endfor %}
                    {% for photo in project['photos'] %}
                    <div class="item {{'active' if ((loop.index0 == 0) and (not 'videos' in project)) }}">
                        <img src="{{photo}}" alt="project-photo" style="width:100%;">
                    </div>
                    {% endfor %}
                </div>

                <!-- Left and right controls -->
                {% if ((project['videos'] | length) + (project['photos'] | length)) > 1 %}
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>

    <div class="wrapper scroll-wrapper">
        <div class="heading">
            <div class="title">{{ project['name'] }}</div>

            <div class="date">{{ project['date'] }}</div>

            <div class="md-chips">
                {% for tag in project['tags'] %}
                <div class="md-chip md-chip-clickable"><a class="md-chip-link" href="/projects?tags={{tag}}">{{tag}}</a>
                </div>
                {% endfor %}
            </div>

            <div class="links">
                {% if 'github' in project %}
                <div><a class="github" href={{project['github']}}>Find on Github</a></div>
                <p>hola github</p>
                {% elif 'arxiv' in project %}
                <div><a class="github" href={{project['arxiv']}}>View on Arxiv</a></div>
                {% elif 'playstore' in project %}
                <div><a class="github" href={{project['playstore']}}>View on Google Play</a></div>
                {% endif %}
                {{ project['short'] }}
                <p>hola</p>
            </div>
        </div>
        <div class="content">{{ project['short'] | safe }}</div>
    </div>

</div>
{% endblock %}

app/templates/projects.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link type="text/css" rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/projects.css') }}">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/card.css') }}">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/chip.css') }}">
{% endblock %}

{% block body %}

{% if tag is not none %}
<div class="row">
    <div class="md-chips md-chips-center col s2 offset-s5">
        <div class="md-chip md-chip-hover">
            <a class="md-chip-link" href="/projects">{{tag}}</a>
            <div class="md-chip-remove"><a href="/projects" class="md-chip-remove-span">x</a></div>
        </div>
    </div>
</div>
{% endif %}

<div class="row cards-container">
    {% for project in projects %}
    {% include "card.html" %}
    {% endfor %}
</div>

{% endblock %}

app/templates/timeline.html
{% extends "base.html" %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<link type="text/css" rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<script src='https://cdnjs.cloudflare.com/ajax/libs/typed.js/1.1.1/typed.min.js'></script>

<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/timeline.css') }}">
<script type="text/javascript" src="{{ url_for('static', filename = 'js/home.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col s12 m4 l8">
                <ul class="list">
                    {% for time in timeline %}
                    <li>
                        <span class="date">{{time['year']}}</span>
                        <span class="title">{{time['name']}}</span>
                        <span class="content">{{time['desc']}}</span>
                    </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


{% endblock %}